title: Enlight
description: "Enlight is a resource aimed to teach anyone to code through building projects. Hosting a wide variety of tutorials and demos, it provides users with sample projects and explains how they work."
url: https://enlight.nyc
markdown: kramdown
highlighter: rouge
host: 0.0.0.0
